### ISSUE TITLE
[QUESTION] Ablauf für Feature-Branch Entwiklung mit Issue

### ISSUE THREAD

**Issue by MatthiasBiermanns** [projekt-fitnessapp/infrastruktur#10]
Wie genau sollte ich die Branches erstellen, damit diese direkt auf ein KanBan Item gemappt sind? Vor allem, wenn noch keine Items im Board sind?

**Comment by lumaghg** [comment]
Wenn noch keine Items im Board sind dann geht das Mapping natürlich nicht, du kannst dir aber für was auch immer du tust einfach ein Issue im Kanban Board anlegen (für Setup oder was auch immer) und dann im Issue unter "Development" auf "Create a branch" klicken. Dazu einfach ein Kanban Ticket ("Draft") erstellen und in ein Issue umwandeln. Dann kannst du in Clockify auch einfach die Nummer von dem Kanban Ticket (z.B. Infrastruktur #1) angeben.

**Comment by MatthiasBiermanns** [comment]
Dankeschön. Wenn der Projektleiter keine Aufgaben verteilt, muss man ja selbst die Initiative ergreifen ;)
