### ISSUE TITLE
[FEATURE] Hello brauche Rechte

### ISSUE THREAD

**Issue by steffenhls** [projekt-fitnessapp/infrastruktur#11]
**Frage:**
Kann mir jemand Write access für das research repo geben? Dankö

**Comment by lumaghg** [comment]
Hallo @steffenhls, ich habe ein Research Team mit dir und Nandini angelegt und euch Write Access gegeben. Falls es trotzdem nicht geht, kannst du das Issue gerne noch einmal öffnen. Ich wünsche dir viel Vergnügen mit deiner neuen Verfügungsgewalt :)
