### ISSUE TITLE
[QUESTION] Kann mir einer von euch Berechtigungen auf backend-docs geben?

### ISSUE THREAD

**Issue by HaseFlrn** [projekt-fitnessapp/infrastruktur#13]
**Frage:**
Hatte mit Matthias Brainstorming gemacht und wollte an der backend-doku arbeiten. Konnte weder auf main pushen noch einen branch öffnen. habe jetzt geforkt und einen PR geöffnet. Wäre nice, wenns nicht immer so umständlich laufen muss.

**Comment by STAT1C-Sy** [comment]
@HaseFlrn gar kein Problem wird gemacht

**Comment by STAT1C-Sy** [comment]
@HaseFlrn geht jetzt?

**Comment by STAT1C-Sy** [comment]
@HaseFlrn wie besprochen gelöst
