### ISSUE TITLE
[BUG] Codecov Report in der Pr Pipeline ist buggy

### ISSUE THREAD

**Issue by lumaghg** [projekt-fitnessapp/infrastruktur#19]
**Was ist passiert:**
Beim öffnen einer PR wird ein leere Code Coverage report erzeugt 
**Was sollte passieren:**
Beim öffnen einer PR sollte ein Code Coverage report mit Werten erzeugt werden
**Wie kann der Fehler reproduziert werden:**
PR gegen main öffnen
**Weitere Anmerkungen:**

**Comment by lumaghg** [comment]
@STAT1C-Sy Wäre gut wenn das bis Mittwoch geht damit wir nen screenshot von nem codecov report in den Vortrag machen können

**Comment by STAT1C-Sy** [comment]
ja kann net garantieren im zweifelsfall einfach aus dem Internet nehmen erstmal

**Comment by STAT1C-Sy** [comment]
schau mal PR von @HaseFlrn an da hat das geklappt mit dem report

**Comment by lumaghg** [comment]
@STAT1C-Sy ah okay dachte das ist ein Bug dass da alles 0% hat

**Comment by lumaghg** [comment]
@STAT1C-Sy Hast du dann das 80% Requirement ausgestellt? In der PR von Flo sind ja 0% coverage und trotzdem passen alle checks

**Comment by STAT1C-Sy** [comment]
@HaseFlrn ne weiß auch nicht wieso dass das net blockiert

**Comment by STAT1C-Sy** [comment]
@lumaghg schau mal in die PR von Flo da hat er den coverage report zumindest mal wunderbar erstellt hoffe, dass das dann ab jetzt funktioniert wir können das ja nochmal beobachten solange das ganze ungeklärt ist lasse ich hier das issue offen

**Comment by lumaghg** [comment]
Glaube das blockiert nicht, wenn sich die Coverage nicht ändert, ich probiere es gleich mal mit ganz vielen console.logs() unter 80 zu bringen auf nem demo branch und schaue ob er blockt

**Comment by STAT1C-Sy** [comment]
@lumaghg klingt sehr vernünftig

**Comment by STAT1C-Sy** [comment]
@lumaghg du hast absolut recht ich habe damals die base auf auto gestellt damit schläg der nur an wenn der letzte commit schon über 80 war also ab jetzt ist scharf geschaltet. Siehe codecov doku https://docs.codecov.com/docs/common-recipe-list#increase-overall-coverage-on-each-pull-request, kann mich jetzt erinnern habe das damals gemacht damit die mal ne Chance haben den Kram zu setupen. Ich würde dann damit jetzt dieses Issue schließen sobald dein Experiment durch ist.

**Comment by lumaghg** [comment]
Jo hat geklappt (backend#30)
