### ISSUE TITLE
[BUG] Test läuft lokal, in der Pipeline nicht.

### ISSUE THREAD

**Issue by HaseFlrn** [projekt-fitnessapp/infrastruktur#21]
**Was ist passiert:**
Test läuft nicht durch -> Error mit Socket
**Was sollte passieren:**
Test läuft durch
**Wie kann der Fehler reproduziert werden:**
push auf branch
**Weitere Anmerkungen:**
[Siehe PR](https://github.com/projekt-fitnessapp/backend/pull/27)

**Comment by STAT1C-Sy** [comment]
@HaseFlrn ich habe dir geantwortet in deiner PR gib mir gerne Rückmeldung ob das verständlich war. Du kannst dir entweder selber ne Lösung überlegen oder bescheid sagen dann können wir ein wenig zusammen Brainstormen :).
