### ISSUE TITLE
[BUG] MongoServerError: cannot create a new database -- already using 100 databases of 100

### ISSUE THREAD

**Issue by HaseFlrn** [projekt-fitnessapp/infrastruktur#25]
**Was ist passiert:**
Lokal und in der Pipeline ->  MongoServerError:  cannot create a new database -- already using 100 databases of 100
**Was sollte passieren:**
Kein Error
**Wie kann der Fehler reproduziert werden:**
FitnessApp/backend> npm run test
**Weitere Anmerkungen:**
![image](https://user-images.githubusercontent.com/72435707/195984854-1dd4e164-f4fb-4fb7-b1ac-0a5d0cb87402.png)

**Comment by STAT1C-Sy** [comment]
@HaseFlrn  sollte behoben sein. wenn es nochmal auftritt einfach folgendes skript in der mongo ausführen: 

db.adminCommand(
{
listDatabases: 1
}
).databases.forEach( dba => { if(dba.name != "admin" && db.name != "local") { db.getSiblingDB(dba.name).dropDatabase() } } )
