### ISSUE TITLE
[BUG] MongoServerError: cannot create a new database -- already using 100 databases of 100 #25

### ISSUE THREAD

**Issue by juengeja** [projekt-fitnessapp/infrastruktur#26]
**Was ist passiert:**
Lokal und in der Pipeline -> MongoServerError: cannot create a new database -- already using 100 databases of 100
Der Fehler tritt wieder auf
**Was sollte passieren:**
Kein Error
**Wie kann der Fehler reproduziert werden:**
npm run test
**Weitere Anmerkungen:**
![image](https://user-images.githubusercontent.com/73344489/196008265-c08d0001-98ad-4e9b-b39f-ffa06b125366.png)

**Comment by STAT1C-Sy** [comment]
@juengeja Duplikat zu https://github.com/projekt-fitnessapp/infrastruktur/issues/25
