### ISSUE TITLE
[FEATURE] Teamwechsel

### ISSUE THREAD

**Issue by TobiasFitzke01** [projekt-fitnessapp/infrastruktur#28]
**Wie ist es aktuell:**
Ich habe das Team gewechselt und bin jetzt im Frontend Team, habe aber noch keine Rechte

**Wie sollte es sein:**
Wäre top wenn ich die entsp. Rechte für Github habe

**Zusätzliche Anmerkungen:**

**Comment by lumaghg** [comment]
Hi @TobiasFitzke01, du solltest die Rechte bekommen haben. Falls dem so ist, schließ bitte dieses Issue. Haben ja letzte Woche gelernt, dass wir das nicht mehr ohne die Zustimmung des Ticketerstellers dürfen ;)
