### ISSUE TITLE
[FEATURE] Email bei erfolgreichem Deployment

### ISSUE THREAD

**Issue by lumaghg** [projekt-fitnessapp/infrastruktur#29]
**Wie ist es aktuell:**
Es gibt keine Nachricht, wenn etwas deployed wird

**Wie sollte es sein:**
Es soll eine Mail geben, wenn ein Deployment erfolgreich ist

**Zusätzliche Anmerkungen:**
Anforderungen aus Meeting vom 01.03.

**Comment by STAT1C-Sy** [comment]
@projekt-fitnessapp/backend man kann notifications für erfolgreiche workflows über die Einstellungen von Github Settings > Notifications im Bereich System > Actions kann man das einstellen
