### ISSUE TITLE
[BUG] Issue Assignments Backend & Frontend fehlerhaft

### ISSUE THREAD

**Issue by lumaghg** [projekt-fitnessapp/infrastruktur#9]
**Was ist passiert:**
Ich habe ein Issue im Backend und Frontend Repo erstellt und Fynn und Robin wurden assigned

**Was sollte passieren:**
projekt-fitnessapp/backend bzw. projekt-fitnessapp/frontend sollen assigned werden.

**Wie kann der Fehler reproduziert werden:**
Ein Issue im Backend / Frontend Repo erstellen

**Weitere Anmerkungen:**
/

**Comment by STAT1C-Sy** [comment]
Ehre das du ein Issue erstellt hast XD @lumaghg

**Comment by lumaghg** [comment]
Ich kann ja nicht allen erzählen ihr müsst die Issues benutzen und es dann selbst nicht tun xD
Außerdem kannst du dann einfach Infrastruktur #9 in Clockify referenzieren

**Comment by STAT1C-Sy** [comment]
Habe ich geändert
